"""empty message

Revision ID: 5b470f1db805
Revises: 
Create Date: 2016-12-21 13:24:22.979261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b470f1db805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('uz_station_code', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'station', ['uz_station_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station', type_='unique')
    op.drop_column('station', 'uz_station_code')
    # ### end Alembic commands ###
